version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/todos
    depends_on:
      - mongo
    volumes:
      - ./api:/app

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  mongo-data:
