- name: Configure Docker Server
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clone the repo
      git:
        repo: https://github.com/YOUR_USERNAME/todo-app-project.git
        dest: /opt/todo-app

    - name: Start the app
      command: docker-compose up -d
      args:
        chdir: /opt/todo-app
